### ISSUE TITLE
Linux build glibc compatibility

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/cling-feedstock#1]
- Launching the current build of cling produced by conda-forge yields:
    ```
    Warning in cling::IncrementalParser::CheckABICompatibility():
      Possible C++ standard library mismatch, compiled with __GLIBCXX__ '20140120'
      Extraction of runtime standard library version was: '20160609'
    ```
    and later on, the interpreter errors on IO operations. (Linux platform...)

- This error does not occur when building the recipe locally since the glibc version is consistent.

    cling has tight constraints in terms of glibc version match between what was used at link time and runtime.

 - We could prevent this by building cling with conda's gcc and libgcc instead of the one of the build container (this might require to build the entire llvm/clang stack like this). Besides, for the resulting cling binary to support modern C++, we would need a more recent version of gcc.

    EDIT: the approach with gcc is blocking on https://github.com/ContinuumIO/anaconda-issues/issues/1465

**Comment by SylvainCorlay** [comment]
^ @jakirkham this specific issue might be a good case for always using conda's gcc instead of the one from the build container.

**Comment by SylvainCorlay** [comment]
@JohanMabille @msarahan I have been working for some time on the conda packaging of the cling C++ interpreter, with some success, but with some limitations.

There is one aspect of it which makes it more difficult than most packages, it is that unlike most libraries making use of the C runtime, cling has more requirements than the usual ABI compatibility. It basically boils down to the fact that the interpreted code must link with exactly the same C runtime that was used to build the interpreter.

A consequence of that is that we must ship this C runtime as a conda package, and make sure that every dependency should be linked with it and not the one of the build bot.

So as soon as we have a gcc package elected to the default or conda-forge channel, compiled packages should make sure that running

    ldd mybinary

does not return anything from /lib or /usr/lib. In fact, this could be a sane policy for conda packages in general.

(Conda packages for linux currently link with system libraries. This may be an issue as soon as the circleci machines building the libraries update to a newer version of the C runtime and become incompatible with the runtime of the clients installing anaconda...)

**Comment by jakirkham** [comment]
Maybe this is a dumb question, but is it possible to just build `cling` with the packaged `clang` compiler? If so, then you would be tied to `libcxx`, which you are already distributing and pinning.

**Comment by SylvainCorlay** [comment]
My understanding is that `llvm` links with the runtime of the host compiler (gcc on linux, msvc on windows).

**Comment by jakirkham** [comment]
I see. So it wouldn't just be building `cling` with the packaged `clang`. One would need to rebuild the whole LLVM stack of packages with the packaged `clang` compiler to even accomplish such a thing. Is that correct?

**Comment by SylvainCorlay** [comment]
Right, this is what I have been doing in the `SylvainCorlay` channel, and need to update...

I was using gcc-6 from salford systems, and all the packages were building with the same recipe as on conda-forge plus a build-time dependency on gcc-6.

**Comment by SylvainCorlay** [comment]
That said, we were hitting other binary compatibility issues with these builds that I made locally with `march=native` and Johan working on a less recent processor.

As per @JohanMabille 's comment, it seems that doing `mtune=generic` and no `march=` option is the way to go.

**Comment by msarahan** [comment]
This looks to me like it requires the same libstdc++ (CXX), not the same glibc.  Where are you getting glibc from?

Solving libstdc++ is much easier, and conda-build 3 introduces good ways to do the pinning.  glibc is something that is not good to ship, and if we can't use the system glibc, I'm worried about this package.  It is strongly tied to kernel versions, and it's also a security risk to have old versions in use.

**Comment by SylvainCorlay** [comment]
I am pretty sure that it requires the same glibc, and not libcxx, unfortunately.

It might be possible to use libstdc++ in LLVM by using `DLLVM_ENABLE_LIBCXX=1` when building the LLVM stack, but I have not been able to successfully use the resulting build for cling so far. However it might be the way to go indeed.

I don't know much about the security implications of shipping the libc, and how it would be different from shipping libcxx.

**Comment by SylvainCorlay** [comment]
Fixed in the rebuild PR.

**Comment by isuruf** [comment]
Why do you think it's glibc when the error message explicitly says GLIBCXX ?

**Comment by SylvainCorlay** [comment]
This warning is generated by the `CheckABICompatibility` function in cling, but it really concerns the version of the STL headers.

Cling requires that the headers used by the interpreted C++ are the ones used to build clang and cling, where the `__GLIBCXX__` macro is defined.

For this reason, cling now has a runtime dependency on `compiler('cxx')`!

**Comment by SylvainCorlay** [comment]
There was some comments by mingwandroid on gitter about the possibility of splitting the STL headers in a separate package.
