### ISSUE TITLE
cling 0.4

### ISSUE THREAD

**Issue by ghost** [conda-forge/cling-feedstock#10]
Hello,

are you planning bringup cling 0.4 version into conda?

Thanks.

**Comment by SylvainCorlay** [comment]
Yes, we are planning a 0.4 version. Although there is an intrinsic issue with the packaging of cling that makes it not very suitable for conda-forge: `cling` requires *exactly* the same C runttime as the one that was used at build time for itself, but also LLVM, clang... This is especially a problem on linux.

From a miniconda, you can get a functional cling build with 

`conda install cling -c QuantStack`

which comes with all the binary compatible builds of the dependencies. It is build with the same recipe as conda-forge except that we ship the version of gcc used to build it.

**Comment by SylvainCorlay** [comment]
@conda-forge please update circle
