### ISSUE TITLE
ImportError: No module named 'clingkernel'

### ISSUE THREAD

**Issue by bjodah** [conda-forge/cling-feedstock#2]
Thank yout @SylvainCorlay for working on this!
I just tried to install this in my conda environment:
```
$ conda install cling
...
The following NEW packages will be INSTALLED:

    clangdev:      3.9.1-cling_3 conda-forge [cling]
    cling:         0.3.post-0    conda-forge [cling]
    cling-patches: 1-0           conda-forge
    libcxx:        3.9.1-0       conda-forge
    llvmdev:       3.9.1-cling_4 conda-forge [cling]
    system:        5.8-2         defaults   
...
```

however, when I create a C++11 notebook the kernel dies with the following printed to the console:
```
[I 20:15:10.037 NotebookApp] Creating new notebook in 
[I 20:15:10.751 NotebookApp] Kernel started: c6dadf90-1628-4e72-82eb-20e3541bdf0c
Traceback (most recent call last):
  File "/opt/users/miniconda3/bin/jupyter-cling-kernel", line 3, in <module>
    from clingkernel import main
ImportError: No module named 'clingkernel'
```

and there doesn't seem to be any "clingkernel" in conda-forge channel:
```
$ conda install clingkernel
...
PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels: 
  - clingkernel

Close matches found; did you mean one of these?

    clingkernel: ipykernel
...
```

**Comment by SylvainCorlay** [comment]
The cling kernel should be installed as part of the `cling` package.

**Comment by SylvainCorlay** [comment]
Are notebook and cling installed in the same conda environment?

**Comment by bjodah** [comment]
Yes, they are both installed in my conda root environment:
```
$ which jupyter
/opt/users/miniconda3/bin/jupyter
$ which cling
/opt/users/miniconda3/bin/cling
```

EDIT: I'm using ubuntu 16.04 (if that matters)

**Comment by bjodah** [comment]
So I'm using miniconda3 so the default python is 3.5 but clingkernel seems to be installed as a python2.7 package:
```
$ find /opt/users/miniconda3/ -iname "clingkernel*"
...
/opt/users/miniconda3/lib/python2.7/site-packages/clingkernel.py
...
```
a simple workaround is to create a Python 2.7 environment:
```
$ conda create -n py27 python=2.7 notebook cling
$ source activate py27
$ jupyter notebook
```

**Comment by SylvainCorlay** [comment]
@bjodah the py27 vs py35 issue should be fixed in the next build, which will be up in the next hour on linux and about a day on os x (the OS X build backlog is about 24 hours long at the moment).

Note that the linux build will still have the LIBC mismatch
