### ISSUE TITLE
Misspelled option

### ISSUE THREAD

**Issue by henryiii** [conda-forge/cling-feedstock#26]
I believe `-DINSTALL_RPATH_USE_LINK_PATH=ON` should be removed or changed to `-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=ON`; it is being ignored in its current spelling, I believe.

**Comment by SylvainCorlay** [comment]
Thanks @henryiii very good catch.

Changing this may actually fix Issue https://github.com/conda-forge/xeus-cling-feedstock/issues/2!

**Comment by chrisburr** [comment]
Was fixed in https://github.com/conda-forge/cling-feedstock/commit/97a1365935a9f1ade6b54726e17fd5faa806ed7f
