### ISSUE TITLE
ERROR in cling::executePrintValue(): cannot pass value!

### ISSUE THREAD

**Issue by bjodah** [conda-forge/cling-feedstock#3]
Using `python=2.7` allows me to create a C++11 notebook.
The example from https://github.com/SylvainCorlay/cling-binder does not work however:

![cling-jupyter](https://cloud.githubusercontent.com/assets/485936/23144589/d6ad8ec6-f7c8-11e6-872b-5f48ab0859c9.png)

It might be related to #1 since I see the following in the console:
```
[I 23:57:33.655 NotebookApp] Kernel restarted: 2725a98c-a398-4032-a630-ce9e38f3f294
Warning in cling::IncrementalParser::CheckABICompatibility():
  Possible C++ standard library mismatch, compiled with __GLIBCXX__ '20140120'
  Extraction of runtime standard library version was: '20160609'
[ClingKernelApp] ERROR | UNKNOWN MESSAGE TYPE: u'comm_open'
```

**Comment by SylvainCorlay** [comment]
Thanks.

The error displayed in the console and link error

```
Warning in cling::IncrementalParser::CheckABICompatibility():
  Possible C++ standard library mismatch, compiled with __GLIBCXX__ '20140120'
  Extraction of runtime standard library version was: '20160609'
```

is actually the same issue as #1.

I am closing this.

The error with the `comm_open` message is a legitimate issue with cling itself.
