### ISSUE TITLE
Marking "cling v0.6 build 0" as broken

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/cling-feedstock#35]
Hello, @conda-forge/core, would it be possible to mark some cling builds as broken? Namely cling 0.6 build 0 on all platforms:

`cling-0.6-h1a24767_0.tar.bz2`
`cling-0.6-h7475705_0.tar.bz2`
`cling-0.6-he513fc3_0.tar.bz2`

**Comment by jjhelmus** [comment]
Done. Can you check that I set the label on the correct files?

**Comment by SylvainCorlay** [comment]
Yes, that is correct!
